import { Inter } from "next/font/google";
import "../globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "交通流量預測",  // Website title
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant-TW">
      <body className={inter.className}>{children}</body>
    </html>
  );
}